"""ThreadService — reading and deleting conversation history.

Listing threads, replaying one and deleting one have nothing to do with driving
an agent: they touch the session database and the toolbox's own stores, never a
model. Keeping them on the runtime object made a class that streams events also
be the class that answers "what did we talk about last week", and the two have
neither shared state nor a shared lifetime.

OWNERSHIP
---------
Every method takes ``user_id``, and passes it *into the query* rather than
filtering afterwards. The difference matters: a thread id is generated by the
client and is therefore guessable, so a mismatch has to be indistinguishable
from a thread that never existed. Filtering after the fact leaks existence
through timing and through the shape of the answer, and it is one forgotten
``if`` away from leaking the content too.

Agno's ``BaseDb`` has taken ``user_id`` on ``get_session``, ``get_sessions`` and
``delete_session`` all along; the toolbox simply was not passing it. Anyone
holding a thread id could read or delete that thread.

``user_id=None`` means single-user mode, where everything belongs to everybody.
That is a legitimate configuration for a local tool, and a serious mistake for a
deployed one, so the transport warns when no resolver is configured rather than
letting the absence of authentication be the silent default.
"""

from __future__ import annotations

import inspect
from collections import defaultdict
from collections.abc import Callable
from typing import Any

from ..core.streamui import CardCatalog
from ..stores.registry import Stores
from .replay import session_to_messages


class FramesUnavailable(RuntimeError):
    """Frame replay was asked for on a runtime that cannot honestly serve it.

    Raised rather than returning an empty list, because "no frames" and "this
    server does not keep frames" look identical to a client and only one of them
    means the conversation is over.
    """


class ThreadService:
    """History over an Agno session database plus the toolbox's own stores.

    Parameters
    ----------
    db:
        Agno session database, or ``None`` for a runtime with no history.
    stores:
        Where the records Agno does not keep live — chiefly injected ``CUSTOM``
        events, which have to be stitched back into a replayed thread.
    catalog:
        The StreamUI schemas, needed to re-parse a stored answer the way it was
        parsed live — the body of a ``text`` block is not JSON, and only the
        catalog knows which blocks those are.
    hidden_tool_names:
        Called per request rather than captured, because filters can be
        registered after this service is constructed.
    """

    def __init__(
        self,
        db: Any = None,
        *,
        stores: Stores | None = None,
        catalog: CardCatalog | None = None,
        hidden_tool_names: Callable[[], set[str]] | None = None,
    ) -> None:
        self.db = db
        self.stores = stores or Stores()
        self.catalog = catalog
        self._hidden_tool_names = hidden_tool_names or (lambda: set())

    async def replay_messages(
        self, thread_id: str, *, user_id: str | None = None
    ) -> list[dict[str, Any]] | None:
        """Rebuild a thread's messages.

        ``None`` for a thread that does not exist *or* is not this user's — the
        two are deliberately the same answer.
        """
        session = await self.get_session(thread_id, user_id=user_id)

        by_run: dict[str, list[dict[str, Any]]] = defaultdict(list)
        if self.stores.custom_events is not None:
            for record in await self.stores.custom_events.list_by_thread(thread_id):
                by_run[str(record.get("runId") or "")].append(
                    {"name": record.get("name"), "value": record.get("value")}
                )

        messages = (
            session_to_messages(
                session,
                custom_events_by_run=dict(by_run),
                hidden_tool_names=self._hidden_tool_names(),
                catalog=self.catalog,
            )
            if session is not None
            else []
        )
        messages.extend(await self._inflight_user_turns(thread_id, session, user_id=user_id))
        if session is None and not messages:
            return None
        return messages

    async def list_threads(self, *, user_id: str | None = None) -> list[dict[str, Any]]:
        """This user's threads, newest first.

        List is a projection from the dedicated ThreadStore backed by the database.
        """
        return await self.stores.threads.list_threads(user_id=user_id)

    async def get_thread(
        self, thread_id: str, *, user_id: str | None = None
    ) -> dict[str, Any] | None:
        """Get a single thread's metadata and status directly from ThreadStore."""
        return await self.stores.threads.get_thread(thread_id, user_id=user_id)

    async def delete_thread(
        self, thread_id: str, *, user_id: str | None = None, hard: bool = False
    ) -> dict[str, Any]:
        """Delete a thread and the records the toolbox added alongside it."""
        deleted_in_store = False
        if getattr(self.stores, "threads", None) is not None:
            deleted_in_store = await self.stores.threads.delete_thread(
                thread_id, user_id=user_id, hard=hard
            )

        deleted_in_db = False
        if self.db is not None:
            try:
                deleted = self.db.delete_session(session_id=thread_id, user_id=user_id)
                if inspect.isawaitable(deleted):
                    deleted = await deleted
                deleted_in_db = bool(deleted)
            except Exception as exc:  # noqa: BLE001
                return {"ok": False, "error": f"{type(exc).__name__}: {exc}"}

        if not deleted_in_store and not deleted_in_db:
            return {"ok": False, "error": "thread not found"}

        result: dict[str, Any] = {"ok": True}
        if not hard:
            result["soft"] = True

        if self.stores.custom_events is not None:
            try:
                await self.stores.custom_events.delete_by_thread(thread_id)
            except Exception as exc:  # noqa: BLE001 - the session is already gone
                result.setdefault("warnings", []).append(f"{type(exc).__name__}: {exc}")
        if self.stores.history_archive is not None:
            try:
                await self.stores.history_archive.delete_by_thread(thread_id)
            except Exception as exc:  # noqa: BLE001
                result.setdefault("warnings", []).append(f"{type(exc).__name__}: {exc}")
        if self.stores.event_log is not None:
            try:
                await self.stores.event_log.delete_thread(thread_id)
            except Exception as exc:  # noqa: BLE001
                result.setdefault("warnings", []).append(f"{type(exc).__name__}: {exc}")
        return result

    async def _inflight_user_turns(
        self, thread_id: str, session: Any, *, user_id: str | None
    ) -> list[dict[str, Any]]:
        """Prompts for runs Agno has not flushed yet.

        The hot log records the user text at ``start``. Without this, a reload
        mid-run shows the assistant stream and an empty question.
        """
        log = self.stores.event_log
        if log is None:
            return []
        known = {
            str(getattr(run, "run_id", "") or "") for run in (getattr(session, "runs", None) or [])
        }
        extra: list[dict[str, Any]] = []
        for record in await log.list_runs(thread_id, user_id=user_id):
            if record.run_id in known:
                continue
            text = str((record.meta or {}).get("input") or "")
            if not text:
                continue
            extra.append({"id": f"u-{record.run_id}", "role": "user", "content": text})
        return extra

    # ── frame-based history ───────────────────────────────────────────────

    async def read_frames(
        self, thread_id: str, *, user_id: str | None = None, after: str | None = None
    ) -> list[dict[str, Any]]:
        """A thread's runs, oldest first, as the frames the client was sent.

        Prefers the history archive (coalesced, durable). Runs still only on the
        hot log — in progress, or not yet archived — are appended from there.
        A hot log alone is allowed: that is Redis replay while the TTL holds.
        After eviction, an empty list here is not "the thread is empty"; the
        client falls back to session messages.
        """
        archive = self.stores.history_archive
        log = self.stores.event_log
        if archive is None and log is None:
            raise FramesUnavailable(
                "frame replay needs a history archive or a RunEventLog; neither "
                "is configured on this runtime"
            )

        cursor_run, cursor_offset = _split_cursor(after)
        seen_cursor = cursor_run is None
        frames: list[dict[str, Any]] = []
        seen_runs: set[str] = set()

        if archive is not None:
            for run_id, events in await archive.list_thread(thread_id, user_id=user_id):
                seen_runs.add(run_id)
                payloads = _archived_frames(run_id, events)
                if not seen_cursor:
                    if run_id != cursor_run:
                        continue
                    seen_cursor = True
                    payloads = _after_offset(payloads, cursor_offset)
                frames.extend(payloads)

        if log is not None:
            for record in await log.list_runs(thread_id, user_id=user_id):
                if record.run_id in seen_runs:
                    continue
                if not seen_cursor:
                    if record.run_id != cursor_run:
                        continue
                    seen_cursor = True
                    run_frames = await log.read(record.run_id, after=cursor_offset)
                else:
                    run_frames = await log.read(record.run_id)
                prompt = str((getattr(record, "meta", None) or {}).get("input") or "")
                out_frames = []
                for frame in run_frames:
                    event_dict = dict(frame.event)
                    if prompt and event_dict.get("type") == "RUN_STARTED":
                        raw_key = "rawEvent" if "rawEvent" in event_dict else "raw_event"
                        raw = dict(event_dict.get(raw_key) or {})
                        if not raw.get("user_input"):
                            raw["user_input"] = prompt
                            raw["input"] = prompt
                            event_dict[raw_key] = raw
                    out_frames.append(
                        {"id": f"{record.run_id}:{frame.offset}", "event": event_dict}
                    )
                frames.extend(out_frames)
        return frames

    # ── session database access ───────────────────────────────────────────

    async def get_session(self, thread_id: str, *, user_id: str | None = None) -> Any:
        if self.db is None:
            return None
        res = self.db.get_session(session_id=thread_id, user_id=user_id)
        if inspect.isawaitable(res):
            res = await res
        return res

    async def get_sessions(self, *, user_id: str | None = None) -> list[Any]:
        if self.db is None:
            return []
        # Prefer Agno's raw rows: list endpoints must not hydrate full RunOutput
        # graphs. Fall back if an older/fake db rejects the kwargs.
        try:
            res = self.db.get_sessions(
                user_id=user_id,
                deserialize=False,
                sort_by="updated_at",
                sort_order="desc",
            )
        except TypeError:
            res = self.db.get_sessions(user_id=user_id)
        if inspect.isawaitable(res):
            res = await res
        if isinstance(res, tuple):
            # Agno returns (rows, total) when deserialize=False.
            res = res[0]
        return list(res or [])


def _archived_frames(run_id: str, events: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [
        {"id": f"{run_id}:{index:012d}", "event": dict(event)}
        for index, event in enumerate(events, start=1)
    ]


def _after_offset(payloads: list[dict[str, Any]], offset: str | None) -> list[dict[str, Any]]:
    if not offset:
        return payloads
    return [payload for payload in payloads if payload["id"].partition(":")[2] > offset]


def _split_cursor(after: str | None) -> tuple[str | None, str | None]:
    if not after or ":" not in after:
        return None, None
    run_id, _, offset = after.partition(":")
    return run_id, offset


__all__ = ["FramesUnavailable", "ThreadService"]
