"""ThreadService — reading and deleting conversation history.

Listing threads, replaying one and deleting one have nothing to do with driving
an agent: they touch the session database and the toolbox's own stores, never a
model. Keeping them on the runtime object made a class that streams events also
be the class that answers "what did we talk about last week", and the two have
neither shared state nor a shared lifetime.

OWNERSHIP
---------
Every method takes ``user_id``, and passes it *into the query* rather than
filtering afterwards. The difference matters: a thread id is generated by the
client and is therefore guessable, so a mismatch has to be indistinguishable
from a thread that never existed. Filtering after the fact leaks existence
through timing and through the shape of the answer, and it is one forgotten
``if`` away from leaking the content too.

Agno's ``BaseDb`` has taken ``user_id`` on ``get_session``, ``get_sessions`` and
``delete_session`` all along; the toolbox simply was not passing it. Anyone
holding a thread id could read or delete that thread.

AGENT SCOPE
-----------
Several runtimes can share one set of tables. Give each its own ``agent_id`` and
every read, replay and delete is confined to that agent's threads, the same way
``user_id`` confines it to one user's: the filter goes into the query, and a
thread owned by another agent is indistinguishable from one that never existed.
``agent_id=None`` leaves the service unscoped (the old behaviour).

``list_threads`` / ``get_thread`` / ``delete_thread`` also take a per-call
``agent_id`` to filter an unscoped service down to one agent. A per-call value
can only narrow: on a scoped service it must equal the scope, and anything else
matches nothing rather than widening or switching it.

``user_id=None`` means single-user mode, where everything belongs to everybody.
That is a legitimate configuration for a local tool, and a serious mistake for a
deployed one, so the transport warns when no resolver is configured rather than
letting the absence of authentication be the silent default.
"""

from __future__ import annotations

import inspect
from collections import defaultdict
from collections.abc import Callable
from typing import Any

from ..core.streamui import CardCatalog
from ..stores.registry import Stores
from .replay import session_to_messages, thread_summary_from_session


class FramesUnavailable(RuntimeError):
    """Frame replay was asked for on a runtime that cannot honestly serve it.

    Raised rather than returning an empty list, because "no frames" and "this
    server does not keep frames" look identical to a client and only one of them
    means the conversation is over.
    """


class ThreadService:
    """History over an Agno session database plus the toolbox's own stores.

    Parameters
    ----------
    db:
        Agno session database, or ``None`` for a runtime with no history.
    stores:
        Where the records Agno does not keep live — chiefly injected ``CUSTOM``
        events, which have to be stitched back into a replayed thread.
    catalog:
        The StreamUI schemas, needed to re-parse a stored answer the way it was
        parsed live — the body of a ``text`` block is not JSON, and only the
        catalog knows which blocks those are.
    hidden_tool_names:
        Called per request rather than captured, because filters can be
        registered after this service is constructed.
    agent_id:
        Confine this service to one agent's threads and sessions. Threads are
        matched on the owner stamped by ``start_turn``; Agno sessions on their
        own ``agent_id``. ``None`` disables the scope.
    """

    def __init__(
        self,
        db: Any = None,
        *,
        stores: Stores | None = None,
        catalog: CardCatalog | None = None,
        hidden_tool_names: Callable[[], set[str]] | None = None,
        agent_id: str | None = None,
    ) -> None:
        self.agent_id = agent_id
        self.db = db
        self.stores = stores or Stores()
        self.catalog = catalog
        self._hidden_tool_names = hidden_tool_names or (lambda: set())

    async def replay_messages(
        self, thread_id: str, *, user_id: str | None = None
    ) -> list[dict[str, Any]] | None:
        """Rebuild a thread's messages.

        ``None`` for a thread that does not exist *or* is not this user's — the
        two are deliberately the same answer.
        """
        session = await self.get_session(thread_id, user_id=user_id)

        by_run: dict[str, list[dict[str, Any]]] = defaultdict(list)
        if self.stores.custom_events is not None:
            for record in await self.stores.custom_events.list_by_thread(thread_id):
                by_run[str(record.get("runId") or "")].append(
                    {"name": record.get("name"), "value": record.get("value")}
                )

        messages = (
            session_to_messages(
                session,
                custom_events_by_run=dict(by_run),
                hidden_tool_names=self._hidden_tool_names(),
                catalog=self.catalog,
            )
            if session is not None
            else []
        )
        messages.extend(await self._inflight_user_turns(thread_id, session, user_id=user_id))
        if session is None and not messages:
            return None
        return messages

    async def list_threads(
        self, *, user_id: str | None = None, agent_id: str | None = None
    ) -> list[dict[str, Any]]:
        """This user's threads, newest first; optionally only one agent's.

        List is a projection from the dedicated ThreadStore backed by the database.
        Falls back to Agno session rows if ThreadStore has no entries.
        """
        scope, allowed = self._narrow(agent_id)
        if not allowed:
            return []
        if getattr(self.stores, "threads", None) is not None:
            try:
                store_threads = await self.stores.threads.list_threads(
                    user_id=user_id, agent_id=scope
                )
                if store_threads:
                    return store_threads
            except Exception:
                pass

        threads: list[dict[str, Any]] = []
        for session in await self.get_sessions(user_id=user_id, agent_id=scope):
            row = thread_summary_from_session(session)
            if row is not None:
                threads.append(row)
        threads.sort(key=lambda t: t.get("updatedAt") or 0, reverse=True)
        return threads

    async def get_thread(
        self, thread_id: str, *, user_id: str | None = None, agent_id: str | None = None
    ) -> dict[str, Any] | None:
        """Get a single thread's metadata and status directly from ThreadStore."""
        scope, allowed = self._narrow(agent_id)
        if not allowed:
            return None
        if getattr(self.stores, "threads", None) is not None:
            try:
                thread = await self.stores.threads.get_thread(
                    thread_id, user_id=user_id, agent_id=scope
                )
                if thread is not None:
                    return thread
            except Exception:
                pass

        session = await self.get_session(thread_id, user_id=user_id, agent_id=scope)
        if session is not None:
            return thread_summary_from_session(session)
        return None

    async def delete_thread(
        self,
        thread_id: str,
        *,
        user_id: str | None = None,
        hard: bool = False,
        agent_id: str | None = None,
    ) -> dict[str, Any]:
        """Delete a thread and the records the toolbox added alongside it."""
        scope, allowed = self._narrow(agent_id)
        if not allowed:
            return {"ok": False, "error": "thread not found"}
        deleted_in_store = False
        if getattr(self.stores, "threads", None) is not None:
            deleted_in_store = await self.stores.threads.delete_thread(
                thread_id, user_id=user_id, hard=hard, agent_id=scope
            )

        deleted_in_db = False
        # Agno's delete_session has no agent filter, so a scoped service must
        # confirm ownership first or it would delete another agent's session.
        owns_session = scope is None or await self.get_session(
            thread_id, user_id=user_id, agent_id=scope
        )
        if self.db is not None and owns_session:
            try:
                deleted = self.db.delete_session(session_id=thread_id, user_id=user_id)
                if inspect.isawaitable(deleted):
                    deleted = await deleted
                deleted_in_db = bool(deleted)
            except Exception as exc:  # noqa: BLE001
                return {"ok": False, "error": f"{type(exc).__name__}: {exc}"}

        if not deleted_in_store and not deleted_in_db:
            return {"ok": False, "error": "thread not found"}

        result: dict[str, Any] = {"ok": True}
        if not hard:
            result["soft"] = True

        if self.stores.custom_events is not None:
            try:
                await self.stores.custom_events.delete_by_thread(thread_id)
            except Exception as exc:  # noqa: BLE001 - the session is already gone
                result.setdefault("warnings", []).append(f"{type(exc).__name__}: {exc}")
        if self.stores.history_archive is not None:
            try:
                await self.stores.history_archive.delete_by_thread(thread_id)
            except Exception as exc:  # noqa: BLE001
                result.setdefault("warnings", []).append(f"{type(exc).__name__}: {exc}")
        if self.stores.event_log is not None:
            try:
                await self.stores.event_log.delete_thread(thread_id)
            except Exception as exc:  # noqa: BLE001
                result.setdefault("warnings", []).append(f"{type(exc).__name__}: {exc}")
        return result

    async def _inflight_user_turns(
        self, thread_id: str, session: Any, *, user_id: str | None
    ) -> list[dict[str, Any]]:
        """Prompts for runs Agno has not flushed yet.

        The hot log records the user text at ``start``. Without this, a reload
        mid-run shows the assistant stream and an empty question.
        """
        log = self.stores.event_log
        if log is None:
            return []
        known = {
            str(getattr(run, "run_id", "") or "") for run in (getattr(session, "runs", None) or [])
        }
        extra: list[dict[str, Any]] = []
        for record in await log.list_runs(thread_id, user_id=user_id):
            if record.run_id in known:
                continue
            text = str((record.meta or {}).get("input") or "")
            if not text:
                continue
            extra.append({"id": f"u-{record.run_id}", "role": "user", "content": text})
        return extra

    # ── frame-based history ───────────────────────────────────────────────

    async def read_frames(
        self, thread_id: str, *, user_id: str | None = None, after: str | None = None
    ) -> list[dict[str, Any]]:
        """A thread's runs, oldest first, as the frames the client was sent.

        Prefers the history archive (coalesced, durable). Runs still only on the
        hot log — in progress, or not yet archived — are appended from there.
        A hot log alone is allowed: that is Redis replay while the TTL holds.
        After eviction, an empty list here is not "the thread is empty"; the
        client falls back to session messages.
        """
        archive = self.stores.history_archive
        log = self.stores.event_log
        if archive is None and log is None:
            raise FramesUnavailable(
                "frame replay needs a history archive or a RunEventLog; neither "
                "is configured on this runtime"
            )

        cursor_run, cursor_offset = _split_cursor(after)
        seen_cursor = cursor_run is None
        frames: list[dict[str, Any]] = []
        seen_runs: set[str] = set()

        if archive is not None:
            for run_id, events in await archive.list_thread(thread_id, user_id=user_id):
                seen_runs.add(run_id)
                payloads = _archived_frames(run_id, events)
                if not seen_cursor:
                    if run_id != cursor_run:
                        continue
                    seen_cursor = True
                    payloads = _after_offset(payloads, cursor_offset)
                frames.extend(payloads)

        if log is not None:
            for record in await log.list_runs(thread_id, user_id=user_id):
                if record.run_id in seen_runs:
                    continue
                if not seen_cursor:
                    if record.run_id != cursor_run:
                        continue
                    seen_cursor = True
                    run_frames = await log.read(record.run_id, after=cursor_offset)
                else:
                    run_frames = await log.read(record.run_id)
                prompt = str((getattr(record, "meta", None) or {}).get("input") or "")
                out_frames = []
                for frame in run_frames:
                    event_dict = dict(frame.event)
                    if prompt and event_dict.get("type") == "RUN_STARTED":
                        raw_key = "rawEvent" if "rawEvent" in event_dict else "raw_event"
                        raw = dict(event_dict.get(raw_key) or {})
                        if not raw.get("user_input"):
                            raw["user_input"] = prompt
                            raw["input"] = prompt
                            event_dict[raw_key] = raw
                    out_frames.append(
                        {"id": f"{record.run_id}:{frame.offset}", "event": event_dict}
                    )
                frames.extend(out_frames)
        return frames

    # ── session database access ───────────────────────────────────────────

    async def get_session(
        self, thread_id: str, *, user_id: str | None = None, agent_id: str | None = None
    ) -> Any:
        if self.db is None:
            return None
        res = self.db.get_session(session_id=thread_id, user_id=user_id)
        if inspect.isawaitable(res):
            res = await res
        scope, allowed = self._narrow(agent_id)
        if res is not None and not (allowed and self._in_scope(res, scope)):
            return None
        return res

    async def get_sessions(
        self, *, user_id: str | None = None, agent_id: str | None = None
    ) -> list[Any]:
        scope, allowed = self._narrow(agent_id)
        if self.db is None or not allowed:
            return []
        # Prefer Agno's raw rows: list endpoints must not hydrate full RunOutput
        # graphs. Fall back if an older/fake db rejects the kwargs.
        kwargs: dict[str, Any] = {
            "user_id": user_id,
            "deserialize": False,
            "sort_by": "updated_at",
            "sort_order": "desc",
        }
        if scope is not None:
            kwargs["component_id"] = scope
        try:
            res = self.db.get_sessions(**kwargs)
        except TypeError:
            res = self.db.get_sessions(user_id=user_id)
        if inspect.isawaitable(res):
            res = await res
        if isinstance(res, tuple):
            # Agno returns (rows, total) when deserialize=False.
            res = res[0]
        # Re-check after the query: an older db may ignore ``component_id``.
        return [s for s in (res or []) if self._in_scope(s, scope)]

    def _narrow(self, agent_id: str | None) -> tuple[str | None, bool]:
        """Combine the service scope with a per-call ``agent_id``.

        Returns ``(effective_agent_id, allowed)``. A per-call value may narrow an
        unscoped service; on a scoped one it must match, else nothing is allowed.
        """
        if self.agent_id is None or agent_id is None or agent_id == self.agent_id:
            return (agent_id if agent_id is not None else self.agent_id), True
        return None, False

    @staticmethod
    def _in_scope(session: Any, agent_id: str | None) -> bool:
        """Whether an Agno session (object or raw row) belongs to ``agent_id``."""
        if agent_id is None:
            return True
        get = session.get if isinstance(session, dict) else lambda k: getattr(session, k, None)
        return agent_id in (get("agent_id"), get("team_id"), get("workflow_id"))


def _archived_frames(run_id: str, events: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [
        {"id": f"{run_id}:{index:012d}", "event": dict(event)}
        for index, event in enumerate(events, start=1)
    ]


def _after_offset(payloads: list[dict[str, Any]], offset: str | None) -> list[dict[str, Any]]:
    if not offset:
        return payloads
    return [payload for payload in payloads if payload["id"].partition(":")[2] > offset]


def _split_cursor(after: str | None) -> tuple[str | None, str | None]:
    if not after or ":" not in after:
        return None, None
    run_id, _, offset = after.partition(":")
    return run_id, offset


__all__ = ["FramesUnavailable", "ThreadService"]
