"""agno-harness — enterprise-level agent scaffolding (Agno Runtime + Relay)."""

from typing import Any

from .app import RelayApp
from .channels import (
    TEAMS_MESSAGES_PATH,
    WEB_AGUI_PATH,
    BaseChannel,
    CLIChannel,
    LarkChannel,
    TeamsAuthError,
    TeamsBotAdapter,
    TeamsChannel,
    TeamsChannelError,
    TeamsCredentialsError,
    TeamsDeliveryError,
    TeamsServiceUrlError,
    WebChannel,
    teams_messaging_endpoint,
)
from .channels.cleaning import html_to_markdown, lark_post_to_markdown, teams_html_to_markdown
from .config import RelayConfig
from .core import (
    EVENT_BLOCK_END,
    EVENT_BLOCK_START,
    EVENT_DEBUG_SUMMARY,
    EVENT_ITEM,
    EVENT_TEXT,
    FENCE_TAG,
    BlockSchema,
    CardCatalog,
    CardSchema,
    CatalogConflict,
    DebugTap,
    EventSequencer,
    HideToolFilter,
    ItemSchema,
    MediaUrl,
    PromptPlugin,
    ProtocolViolation,
    ProtocolViolationError,
    QueryEnvelope,
    QueryTurn,
    RedactFilter,
    SequencerMode,
    SourceContextPlugin,
    StreamUIBlock,
    StreamUIFenceParser,
    StreamUIItem,
    ToolFilter,
    TransformResultFilter,
    UserQueryBuilder,
    default_builder,
    parse_streamui_text,
)
from .core.attachment import AttachmentProcessor, InboundAttachment
from .core.channel import Channel, ChannelEvent, OutboundMessage
from .core.chimein import (
    AlwaysChimeInPolicy,
    ChimeInPolicy,
    KeywordChimeInPolicy,
    MentionOnlyPolicy,
)
from .db import (
    AgnoHarnessDb,
    AgnoHarnessPostgresDb,
    AgnoHarnessSqliteDb,
    AlembicMigrator,
    MissingHarnessTablesError,
)
from .helpers import (
    begin_lark_app_registration,
    generate_lark_setup_guide,
    generate_teams_manifest_template,
    interactive_lark_onboarding,
    interactive_teams_onboarding,
    poll_lark_app_registration,
    save_env_file,
)
from .knowledge import MarkdownKnowledge
from .logging import (
    RelayConsoleFormatter,
    RelayJsonFormatter,
    get_relay_logger,
    setup_relay_logging,
)
from .runtime import (
    EVENT_RUN_CANCELLED,
    EVENT_RUN_PAUSED,
    EVENT_SUBAGENT_END,
    EVENT_SUBAGENT_START,
    EVENT_THREAD_TITLE,
    TRACE_DIR_ENV,
    AgentRunner,
    AgentRuntime,
    BridgeModule,
    ChunkRecorder,
    EventParser,
    EventTranslator,
    Module,
    ModuleConflict,
    ModuleRegistry,
    PostRunHook,
    PreRunHook,
    RunScope,
    RunTracer,
    SmartCompressionManager,
    StateTracker,
    StoragePairingError,
    StreamUIModule,
    SubAgentBus,
    SubStream,
    ThreadService,
    attach_checkpoint_to_session,
    close_dangling_tool_calls,
    compression_events_parser,
    emit_item,
    emit_text,
    install_sealed_history_hook,
    make_checkpoint_hook,
    make_run_scope,
    make_thread_title_hook,
    make_thread_title_pre_hook,
    reasoning_content_parser,
    sanitize_reason,
    seal_session_run,
    setup_thread_titles,
    strip_stream_ui,
    structural_prune,
    subagent_steps_parser,
    substream,
    ui_block,
)
from .runtime.longrun import LongRunManager
from .sessions import (
    ConversationKey,
    InMemorySessionStore,
    SessionManager,
    SessionRecord,
    SQLAlchemySessionStore,
    SQLiteSessionStore,
)
from .sinks import AuditRecord, BaseSink, InMemorySink, PostgresSink, SQLAlchemySink, SQLiteSink
from .skills import (
    SkillDefinition,
    SkillError,
    SkillManager,
    SkillParseError,
    SkillValidationError,
)
from .stores import (
    DEFAULT_TABLE_PREFIX,
    ActionRecordMixin,
    BaseThreadStore,
    CustomEventMixin,
    CustomEventStore,
    DefaultRelayBase,
    InMemoryActionStore,
    InMemoryCustomEventStore,
    InMemoryThreadStore,
    MessageAuditMixin,
    ResumeMode,
    RunArchiveMixin,
    RunFrameMixin,
    RunRecordMixin,
    SessionRecordMixin,
    SQLAlchemyActionStore,
    SQLAlchemyThreadStore,
    StoreRegistry,
    Stores,
    ThreadRecordMixin,
    apply_table_prefix,
    get_or_create_thread_model,
    harness_metadata,
    include_harness,
    numbered_revisions,
    register_harness_models,
    table_name,
)
from .stream import MessageCollector, StreamMode, ThrottledStreamBuffer
from .tools import (
    STATE_TO_MARKER,
    TODO_MARKERS,
    ArtifactCard,
    DiffCard,
    ExaTools,
    PresentationDeck,
    SerperTools,
    SlideProgressItem,
    StreamingArtifactToolkit,
    SubAgentTool,
    SubAgentToolkit,
    TodoToolkit,
    WorkspaceToolkit,
    append_artifact,
    apply_patch_block,
    apply_search_replace,
    emit_artifact,
    format_todo_list,
    parse_todo_list,
    patch_artifact,
    read_artifact_section,
    stream_artifact,
    todo_write,
)

__version__ = "0.2.3"


def __getattr__(name: str) -> Any:
    """Expose optional layers lazily without importing what they depend on."""
    if name in ("make_agui_router", "make_relay_router", "ConfigurationError"):
        from .transport.router import ConfigurationError, make_agui_router, make_relay_router

        if name == "make_agui_router":
            return make_agui_router
        if name == "make_relay_router":
            return make_relay_router
        return ConfigurationError
    if name == "RelayServer":
        from .server import RelayServer

        return RelayServer
    if name in ("setup_otlp", "ObservabilityModule"):
        from . import observability

        return getattr(observability, name)
    if name == "RedisRunEventLog":
        from .stores.redis_log import RedisRunEventLog

        return RedisRunEventLog
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "ActionRecordMixin",
    "EVENT_BLOCK_END",
    "EVENT_BLOCK_START",
    "EVENT_DEBUG_SUMMARY",
    "EVENT_ITEM",
    "EVENT_RUN_CANCELLED",
    "EVENT_RUN_PAUSED",
    "EVENT_SUBAGENT_END",
    "EVENT_SUBAGENT_START",
    "EVENT_TEXT",
    "EVENT_THREAD_TITLE",
    "FENCE_TAG",
    "STATE_TO_MARKER",
    "TODO_MARKERS",
    "TRACE_DIR_ENV",
    "AgentRunner",
    "AgentRuntime",
    "AgnoHarnessDb",
    "AgnoHarnessPostgresDb",
    "AgnoHarnessSqliteDb",
    "AlembicMigrator",
    "AlwaysChimeInPolicy",
    "ArtifactCard",
    "AttachmentProcessor",
    "AuditRecord",
    "BaseChannel",
    "BaseSink",
    "BaseThreadStore",
    "BlockSchema",
    "BridgeModule",
    "CLIChannel",
    "CardCatalog",
    "CardSchema",
    "CatalogConflict",
    "Channel",
    "ChannelEvent",
    "ChimeInPolicy",
    "ChunkRecorder",
    "ConfigurationError",
    "ConversationKey",
    "CustomEventMixin",
    "CustomEventStore",
    "DebugTap",
    "DEFAULT_TABLE_PREFIX",
    "DefaultRelayBase",
    "DiffCard",
    "apply_table_prefix",
    "harness_metadata",
    "include_harness",
    "numbered_revisions",
    "register_harness_models",
    "table_name",
    "default_builder",
    "EventParser",
    "EventSequencer",
    "EventTranslator",
    "HideToolFilter",
    "InMemoryActionStore",
    "InMemoryCustomEventStore",
    "InMemorySessionStore",
    "InMemorySink",
    "InMemoryThreadStore",
    "InboundAttachment",
    "ItemSchema",
    "KeywordChimeInPolicy",
    "LarkChannel",
    "LongRunManager",
    "MarkdownKnowledge",
    "MediaUrl",
    "MentionOnlyPolicy",
    "MessageAuditMixin",
    "MessageCollector",
    "MissingHarnessTablesError",
    "Module",
    "ModuleConflict",
    "ModuleRegistry",
    "ObservabilityModule",
    "OutboundMessage",
    "PostRunHook",
    "PostgresSink",
    "PreRunHook",
    "PresentationDeck",
    "PromptPlugin",
    "ProtocolViolation",
    "ProtocolViolationError",
    "QueryEnvelope",
    "QueryTurn",
    "RedactFilter",
    "RedisRunEventLog",
    "RelayApp",
    "RelayConfig",
    "RelayConsoleFormatter",
    "RelayJsonFormatter",
    "RelayServer",
    "ResumeMode",
    "RunArchiveMixin",
    "RunFrameMixin",
    "RunRecordMixin",
    "RunScope",
    "RunTracer",
    "SQLAlchemyActionStore",
    "SQLAlchemySessionStore",
    "SQLAlchemySink",
    "SQLiteSessionStore",
    "SQLiteSink",
    "begin_lark_app_registration",
    "generate_lark_setup_guide",
    "generate_teams_manifest_template",
    "get_relay_logger",
    "interactive_lark_onboarding",
    "interactive_teams_onboarding",
    "poll_lark_app_registration",
    "save_env_file",
    "setup_relay_logging",
    "SequencerMode",
    "ExaTools",
    "SerperTools",
    "SessionManager",
    "SessionRecord",
    "SessionRecordMixin",
    "ThreadRecordMixin",
    "SQLAlchemyActionStore",
    "SQLAlchemyThreadStore",
    "get_or_create_thread_model",
    "SkillDefinition",
    "SkillError",
    "SkillManager",
    "SkillParseError",
    "SkillValidationError",
    "SlideProgressItem",
    "SmartCompressionManager",
    "SourceContextPlugin",
    "StateTracker",
    "StoragePairingError",
    "StoreRegistry",
    "Stores",
    "StreamMode",
    "StreamUIBlock",
    "StreamUIFenceParser",
    "StreamUIItem",
    "StreamUIModule",
    "StreamingArtifactToolkit",
    "SubAgentBus",
    "SubAgentTool",
    "SubAgentToolkit",
    "SubStream",
    "TEAMS_MESSAGES_PATH",
    "WEB_AGUI_PATH",
    "TeamsAuthError",
    "TeamsBotAdapter",
    "TeamsChannel",
    "TeamsChannelError",
    "TeamsCredentialsError",
    "TeamsDeliveryError",
    "TeamsServiceUrlError",
    "ThreadService",
    "ThrottledStreamBuffer",
    "TodoToolkit",
    "ToolFilter",
    "TransformResultFilter",
    "UserQueryBuilder",
    "WebChannel",
    "WorkspaceToolkit",
    "__version__",
    "append_artifact",
    "apply_patch_block",
    "apply_search_replace",
    "attach_checkpoint_to_session",
    "close_dangling_tool_calls",
    "compression_events_parser",
    "emit_artifact",
    "emit_item",
    "emit_text",
    "format_todo_list",
    "html_to_markdown",
    "install_sealed_history_hook",
    "lark_post_to_markdown",
    "make_agui_router",
    "make_checkpoint_hook",
    "make_relay_router",
    "make_run_scope",
    "make_thread_title_hook",
    "make_thread_title_pre_hook",
    "parse_streamui_text",
    "parse_todo_list",
    "patch_artifact",
    "read_artifact_section",
    "reasoning_content_parser",
    "sanitize_reason",
    "seal_session_run",
    "setup_otlp",
    "setup_thread_titles",
    "stream_artifact",
    "strip_stream_ui",
    "structural_prune",
    "subagent_steps_parser",
    "substream",
    "teams_html_to_markdown",
    "teams_messaging_endpoint",
    "todo_write",
    "ui_block",
]
