"""agno-relay — Universal Multi-Channel Production Gateway for AGNO Agents."""

from typing import Any

from .app import RelayApp
from .channels import BaseChannel, CLIChannel, LarkChannel, TeamsChannel, WebChannel
from .core import (
    EVENT_BLOCK_END,
    EVENT_BLOCK_START,
    EVENT_DEBUG_SUMMARY,
    EVENT_ITEM,
    EVENT_TEXT,
    FENCE_TAG,
    BlockSchema,
    CardCatalog,
    CardSchema,
    CatalogConflict,
    DebugTap,
    EventSequencer,
    HideToolFilter,
    ItemSchema,
    MediaUrl,
    ProtocolViolation,
    ProtocolViolationError,
    RedactFilter,
    SequencerMode,
    StreamUIBlock,
    StreamUIFenceParser,
    StreamUIItem,
    ToolFilter,
    TransformResultFilter,
    parse_streamui_text,
)
from .core.channel import Channel, ChannelEvent, OutboundMessage
from .runtime import (
    EVENT_RUN_CANCELLED,
    EVENT_RUN_PAUSED,
    EVENT_SUBAGENT_END,
    EVENT_SUBAGENT_START,
    EVENT_THREAD_TITLE,
    TRACE_DIR_ENV,
    AgentRunner,
    AguiRuntime,
    BridgeModule,
    ChunkRecorder,
    EventParser,
    EventTranslator,
    Module,
    ModuleConflict,
    ModuleRegistry,
    PostRunHook,
    PreRunHook,
    RunScope,
    RunTracer,
    SmartCompressionManager,
    StateTracker,
    StreamUIModule,
    SubAgentBus,
    SubStream,
    ThreadService,
    attach_checkpoint_to_session,
    close_dangling_tool_calls,
    compression_events_parser,
    emit_item,
    emit_text,
    install_sealed_history_hook,
    make_checkpoint_hook,
    make_run_scope,
    make_thread_title_hook,
    make_thread_title_pre_hook,
    reasoning_content_parser,
    sanitize_reason,
    seal_session_run,
    setup_thread_titles,
    strip_stream_ui,
    structural_prune,
    subagent_steps_parser,
    substream,
    ui_block,
)
from .sessions import ConversationKey, InMemorySessionStore, SessionManager, SessionRecord
from .sinks import AuditRecord, BaseSink, InMemorySink, SQLiteSink
from .skills import (
    SkillDefinition,
    SkillError,
    SkillManager,
    SkillParseError,
    SkillValidationError,
)
from .stores import (
    CustomEventMixin,
    CustomEventStore,
    InMemoryCustomEventStore,
    StoreRegistry,
    Stores,
)
from .stream import MessageCollector, StreamMode, ThrottledStreamBuffer
from .tools import (
    STATE_TO_MARKER,
    TODO_MARKERS,
    ArtifactCard,
    PresentationDeck,
    SerperTools,
    SlideProgressItem,
    StreamingArtifactToolkit,
    SubAgentTool,
    SubAgentToolkit,
    TodoToolkit,
    append_artifact,
    emit_artifact,
    format_todo_list,
    parse_todo_list,
    patch_artifact,
    read_artifact_section,
    stream_artifact,
    todo_write,
)

__version__ = "0.1.0"


def __getattr__(name: str) -> Any:
    """Expose optional layers lazily without importing what they depend on."""
    if name == "make_agui_router":
        from .transport.router import make_agui_router

        return make_agui_router
    if name in ("setup_otlp", "ObservabilityModule"):
        from . import observability

        return getattr(observability, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "EVENT_BLOCK_END",
    "EVENT_BLOCK_START",
    "EVENT_DEBUG_SUMMARY",
    "EVENT_ITEM",
    "EVENT_RUN_CANCELLED",
    "EVENT_RUN_PAUSED",
    "EVENT_SUBAGENT_END",
    "EVENT_SUBAGENT_START",
    "EVENT_TEXT",
    "EVENT_THREAD_TITLE",
    "FENCE_TAG",
    "STATE_TO_MARKER",
    "TODO_MARKERS",
    "TRACE_DIR_ENV",
    "AgentRunner",
    "AguiRuntime",
    "ArtifactCard",
    "AuditRecord",
    "BaseChannel",
    "BaseSink",
    "BlockSchema",
    "BridgeModule",
    "CLIChannel",
    "CardCatalog",
    "CardSchema",
    "CatalogConflict",
    "Channel",
    "ChannelEvent",
    "ChunkRecorder",
    "ConversationKey",
    "CustomEventMixin",
    "CustomEventStore",
    "DebugTap",
    "EventParser",
    "EventSequencer",
    "EventTranslator",
    "HideToolFilter",
    "InMemoryCustomEventStore",
    "InMemorySessionStore",
    "InMemorySink",
    "ItemSchema",
    "LarkChannel",
    "MediaUrl",
    "MessageCollector",
    "Module",
    "ModuleConflict",
    "ModuleRegistry",
    "ObservabilityModule",
    "OutboundMessage",
    "PostRunHook",
    "PreRunHook",
    "PresentationDeck",
    "ProtocolViolation",
    "ProtocolViolationError",
    "RedactFilter",
    "RelayApp",
    "RunScope",
    "RunTracer",
    "SQLiteSink",
    "SequencerMode",
    "SerperTools",
    "SessionManager",
    "SessionRecord",
    "SkillDefinition",
    "SkillError",
    "SkillManager",
    "SkillParseError",
    "SkillValidationError",
    "SlideProgressItem",
    "SmartCompressionManager",
    "StateTracker",
    "StoreRegistry",
    "Stores",
    "StreamMode",
    "StreamUIBlock",
    "StreamUIFenceParser",
    "StreamUIItem",
    "StreamUIModule",
    "StreamingArtifactToolkit",
    "SubAgentBus",
    "SubAgentTool",
    "SubAgentToolkit",
    "SubStream",
    "TeamsChannel",
    "ThreadService",
    "ThrottledStreamBuffer",
    "TodoToolkit",
    "ToolFilter",
    "TransformResultFilter",
    "WebChannel",
    "__version__",
    "append_artifact",
    "attach_checkpoint_to_session",
    "close_dangling_tool_calls",
    "compression_events_parser",
    "emit_artifact",
    "emit_item",
    "emit_text",
    "format_todo_list",
    "install_sealed_history_hook",
    "make_agui_router",
    "make_checkpoint_hook",
    "make_run_scope",
    "make_thread_title_hook",
    "make_thread_title_pre_hook",
    "parse_streamui_text",
    "parse_todo_list",
    "patch_artifact",
    "read_artifact_section",
    "reasoning_content_parser",
    "sanitize_reason",
    "seal_session_run",
    "setup_otlp",
    "setup_thread_titles",
    "stream_artifact",
    "strip_stream_ui",
    "structural_prune",
    "subagent_steps_parser",
    "substream",
    "todo_write",
    "ui_block",
]
